### PR TITLE
Gradle update: 3.5.1

### PR DESCRIPTION
**Pull request by jubeira**
Upgrading Gradle version to 3.5.1.

### CODE REVIEW

**Comment by gb96** [comment]
I tried applying this PR in the indigo branch and it works fine.

I also went a step further and tried latest Gradle version 4.6.  That also seems to work fine.

Is there a reason to prefer 3.5.1 over 4.6 for this project?

Actually I think Gradle 4.6 works okay with Java 9, but Gradle 3.5.1 is broken for Java 9.  This would be a good reason to upgrade to Gradle 4.6

**Comment by gb96** [comment]
See also [rosjava_build_tools/pull/35](https://github.com/rosjava/rosjava_build_tools/pull/35)

**Comment by jubeira** [comment]
Hi @gb96,

I think you may try that, but I had a problem when using Gradle 4.x on Android projects. It's actually an annoying detail: Gradle 4.x uses Android plugin 3.x, which needs Android Build tools 26+. This version of the build tools removed the `android` command from the SDK, which is used by the command line tools to create projects (see https://github.com/rosjava/rosjava_build_tools/issues/31).

I would prefer to keep all the projects with the same Gradle version. Do you need Java 9? IMHO, I would:
- Update to Gradle 3.5.1, which is already an improvement
- Try to fix command line tools for Android (i.e. don't depend on `android` command which was removed)
- Upgradle Gradle to 4.x

**Comment by gb96** [comment]
Hi @jubeira I understand the Android/Gradle issues much better now, thanks.  My project is not Android so Gradle 4.6 and Java 9 work well for me.

**Comment by ernestmc** [comment]
lgtm

**Pull request merged**
